---

- name: Run IOS ommands on remote devices
  hosts: routers
  connection: local
  gather_facts: False

  vars:
    cli:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: cli
        
    run_commands:
      - sh clock
      - sh run
      - sh version
      - sh cdp nei
      - sh proc cpu history
      - sh ip protocols
      - sh ip route
      - sh ntp status
      - sh logging

  tasks:
    - name: Run show version
      ios_command:
        commands: "{{run_commands}}"
        provider: "{{ cli }}"
        interval: 2
        
      # Save the output to a file  
      register: output
    - local_action: copy content="{{ output.stdout }}" dest="/home/Ansible/output.txt"






 
